# Generated by Django 5.2.16 on 2026-07-28 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_organization_organizatio_status_e97117_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_email', models.CharField(blank=True, default='', max_length=254)),
                ('actor_type', models.CharField(default='system', max_length=20)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(blank=True, default='', max_length=80)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, default='', max_length=240)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='accounts.organization')),
            ],
            options={
                'db_table': 'audit_events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_event_organiz_d8584f_idx'), models.Index(fields=['action', '-created_at'], name='audit_event_action_56027e_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_event_object__495694_idx'), models.Index(fields=['actor', '-created_at'], name='audit_event_actor_i_cc925f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_type__in', ('platform', 'agency', 'customer', 'system'))), name='audit_actor_type_valid')],
            },
        ),
    ]
