# Generated by Django 5.2.16 on 2026-07-22 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EsimProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('iccid_encrypted', models.BinaryField(blank=True, null=True)),
                ('iccid_hash', models.BinaryField(blank=True, max_length=32, null=True, unique=True)),
                ('iccid_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('smdp_address_encrypted', models.BinaryField(blank=True, null=True)),
                ('activation_code_encrypted', models.BinaryField(blank=True, null=True)),
                ('qr_payload_encrypted', models.BinaryField(blank=True, null=True)),
                ('encryption_key_version', models.IntegerField(blank=True, null=True)),
                ('total_data_bytes', models.BigIntegerField(blank=True, null=True)),
                ('remaining_data_bytes', models.BigIntegerField(blank=True, null=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_payload_redacted', models.JSONField(default=dict)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='esim_profile', to='orders.orderitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='esim_profiles', to='catalog.supplier')),
            ],
            options={
                'db_table': 'esim_profiles',
            },
        ),
        migrations.CreateModel(
            name='SupplierEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=60)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('correlation_id', models.UUIDField()),
                ('supplier_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('request_data_redacted', models.JSONField(blank=True, null=True)),
                ('response_data_redacted', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=120, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('esim_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_events', to='esims.esimprofile')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_events', to='orders.orderitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalog.supplier')),
            ],
            options={
                'db_table': 'supplier_events',
            },
        ),
        migrations.AddConstraint(
            model_name='esimprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'provisioning', 'ready', 'installed', 'active', 'expired', 'failed', 'cancelled', 'manual_review'))), name='esim_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='esimprofile',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_data_bytes__isnull', True), ('remaining_data_bytes__gte', 0), _connector='OR'), name='esim_remaining_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='esimprofile',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_data_bytes__isnull', True), ('total_data_bytes__isnull', True), ('remaining_data_bytes__lte', models.F('total_data_bytes')), _connector='OR'), name='esim_remaining_le_total'),
        ),
        migrations.AddConstraint(
            model_name='esimprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('supplier_reference__isnull', False)), fields=('supplier', 'supplier_reference'), name='unique_supplier_reference'),
        ),
        migrations.AddIndex(
            model_name='supplierevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='supplier_ev_status_181efb_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'processing', 'retrying', 'succeeded', 'failed', 'cancelled', 'manual_review'))), name='supplier_event_status_valid'),
        ),
    ]
