# Generated by Django 5.2.16 on 2026-07-22 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_topupproduct'),
        ('esims', '0001_initial'),
        ('orders', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('esim_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_fulfillments', to='esims.esimprofile')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='topup_fulfillment', to='orders.orderitem')),
                ('topup_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='catalog.topupproduct')),
            ],
            options={
                'db_table': 'topup_fulfillments',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'processing', 'completed', 'failed', 'cancelled', 'refunded'))), name='topup_fulfillment_status_valid')],
            },
        ),
    ]
