# Generated by Django 5.2.16 on 2026-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esims', '0002_topupfulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimprofile',
            name='qr_code_url_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esimprofile',
            name='short_url_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esimprofile',
            name='supplier_order_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
