# Generated by Django 5.2.16 on 2026-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esims', '0003_esimprofile_qr_code_url_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='esimprofile',
            name='esim_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='esimprofile',
            name='smdp_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
