import hashlib
from datetime import timedelta
import json
import logging

from django.db import transaction
from django.db.models import Sum
from django.utils import timezone

from apps.accounts.services import create_commission_for_order, reverse_commission_for_order
from apps.common.exceptions import Conflict, PaymentMismatch, RefundLimitExceeded
from apps.esims.services import enqueue_provisioning_for_order
from apps.orders.models import Order, OrderItem
from apps.orders.notifications import queue_notification
from apps.orders.services import consume_promo_for_order, release_promo_for_order

from . import stripe as gateway_module
from .models import Payment, Refund, RefundItem, WebhookEvent

logger = logging.getLogger(__name__)


def create_payment_intent_for_order(order):
    if order.payment_status == "paid":
        raise Conflict(
            message="This order has already been paid.",
            error_code="payment_already_completed",
        )
    if order.status != "pending_payment":
        raise Conflict(message="This order is not awaiting payment.")

    if order.total_minor == 0:
        with transaction.atomic():
            _complete_zero_total(order.id)
        return {"zero_total": True, "client_secret": None, "payment_status": "paid"}

    idempotency_key = f"pi:{order.id}"
    gateway = gateway_module.get_gateway()
    intent = gateway.create_payment_intent(
        amount_minor=order.total_minor,
        currency=order.currency,
        metadata={"order_id": str(order.id), "order_number": order.order_number},
        idempotency_key=idempotency_key,
    )
    payment, _ = Payment.objects.get_or_create(
        idempotency_key=idempotency_key,
        defaults={
            "order": order,
            "provider": "stripe",
            "provider_payment_id": intent["id"],
            "amount_minor": order.total_minor,
            "currency": order.currency,
            "status": "processing",
        },
    )
    return {
        "client_secret": intent["client_secret"],
        "payment_id": str(payment.id),
        "amount_minor": order.total_minor,
        "currency": order.currency,
    }


def handle_webhook_event(payload_bytes, sig_header):
    gateway = gateway_module.get_gateway()
    try:
        event = gateway.construct_event(payload_bytes, sig_header)
    except gateway_module.SignatureVerificationError as exc:
        # Deliberately no database row. The endpoint is public and unauthenticated, so
        # persisting one row per rejected request turns the cheapest possible failure into
        # unbounded writes on the primary database. A log line carries the same forensic
        # signal without letting anonymous traffic consume storage.
        #
        # Stripe's own message is included because "invalid signature" alone cannot be
        # acted on — it collapses causes with completely different fixes into one string:
        #
        #   "No signatures found matching the expected signature"  -> wrong secret
        #   "Timestamp outside the tolerance zone"                 -> clock skew or a late
        #                                                             retry; the secret is
        #                                                             fine and changing it
        #                                                             makes things worse
        #   "Unable to extract timestamp and signatures"           -> header missing or
        #                                                             mangled in transit
        #
        # A live rejection was debugged against this log line and it could not distinguish
        # any of the three, so the secret was suspected for hours while the fix might have
        # been elsewhere. The message is generated by Stripe's library from the header and
        # the local secret; it never contains the secret or any payload data.
        #
        # `signed` and the byte count stay because a request that reaches this with NO
        # signature header at all is unsigned traffic hitting a public endpoint, which is
        # a different situation from a genuine Stripe delivery failing to verify.
        logger.warning(
            "Rejected Stripe webhook: %s (%d bytes, signature header %s)",
            exc,
            len(payload_bytes or b""),
            "present" if sig_header else "MISSING",
        )
        return {"ok": False, "status": 400}

    event_id = event["id"]
    event_type = event["type"]
    webhook, created = WebhookEvent.objects.get_or_create(
        provider="stripe",
        external_event_id=event_id,
        defaults={
            "event_type": event_type,
            "payload_redacted": _redact(event),
            "signature_valid": True,
            "status": "received",
            "received_at": timezone.now(),
        },
    )
    if not created and webhook.status == "processed":
        return {"ok": True, "status": 200}

    try:
        with transaction.atomic():
            _dispatch(event_type, event)
    except PaymentMismatch as exc:
        # Reached only after the transaction above has rolled back, so these writes are
        # in autocommit and actually survive. Quarantining the payment here is the point:
        # a signed event that does not reconcile must leave the payment visibly failed,
        # not sitting at "processing" forever with the failure recorded only on the
        # webhook row that operators do not watch.
        payment_id = getattr(exc, "payment_id", None)
        if payment_id is not None:
            Payment.objects.filter(pk=payment_id, status="processing").update(
                status="failed", failure_code="reconciliation_mismatch"
            )
        webhook.status = "failed"
        webhook.last_error = str(exc.message)
        webhook.attempt_count += 1
        webhook.save(update_fields=["status", "last_error", "attempt_count", "updated_at"])
        return {"ok": False, "status": 409}

    webhook.status = "processed"
    webhook.processed_at = timezone.now()
    webhook.save(update_fields=["status", "processed_at", "updated_at"])
    return {"ok": True, "status": 200}


#: Event types we deliberately ignore. Anything outside this set and the handled set is
#: logged loudly rather than silently absorbed — a 200 tells Stripe "dealt with", and it
#: never retries. Absorbing a dispute that way loses the only notification we get.
_IGNORED_EVENT_TYPES = frozenset({
    "payment_intent.created",
    "payment_intent.processing",
    "payment_intent.requires_action",
    "charge.succeeded",
    "charge.updated",
    "charge.pending",
})


def _dispatch(event_type, event):
    obj = event["data"]["object"]
    if event_type == "payment_intent.succeeded":
        _handle_succeeded(obj)
    elif event_type == "payment_intent.payment_failed":
        _handle_failed(obj)
    elif event_type in ("refund.updated", "refund.failed", "charge.refund.updated"):
        _handle_refund_update(obj)
    elif event_type in _IGNORED_EVENT_TYPES:
        return
    else:
        # Disputes and chargebacks land here. We have no automated handling yet, so the
        # only safe behaviour is to make them impossible to miss: money may be leaving.
        logger.error(
            "Unhandled Stripe event %s (object %s) — needs manual review",
            event_type, obj.get("id"),
        )


def _handle_refund_update(refund_obj):
    """Finalise a refund that the gateway completed asynchronously.

    ``create_refund`` stores anything other than an immediate success as ``processing``.
    Without this, Stripe returns the customer's money and nothing changes locally — for
    ever. The order stays paid, commission stays payable, and no refund email is sent,
    while the admin UI shows the refund as successful.
    """
    provider_refund_id = refund_obj.get("id")
    if not provider_refund_id:
        raise PaymentMismatch(message="Refund event carried no refund id.")

    refund = (
        Refund.objects.select_for_update()
        .filter(provider="stripe", provider_refund_id=provider_refund_id)
        .first()
    )
    if refund is None:
        raise PaymentMismatch(message="No local refund matches this event.")
    if refund.status == "succeeded":
        return  # already finalised; Stripe retries are expected

    status = str(refund_obj.get("status") or "").lower()
    if status == "succeeded":
        payment = Payment.objects.select_for_update().get(pk=refund.payment_id)
        order = Order.objects.select_for_update().get(pk=payment.order_id)
        refund.status = "succeeded"
        refund.completed_at = timezone.now()
        refund.save(update_fields=["status", "completed_at", "updated_at"])
        _apply_successful_refund(payment, order, refund.amount_minor)
        queue_notification(
            template_code="refund-confirmation",
            recipient=order.customer_email,
            idempotency_key=f"notify:refund-confirmation:{refund.id}",
            user=order.user,
            order=order,
        )
    elif status in ("failed", "canceled", "cancelled"):
        # The money did not move. Releasing the reservation lets the balance be refunded
        # again rather than staying locked against a refund that never happened.
        refund.status = "failed" if status == "failed" else "cancelled"
        refund.save(update_fields=["status", "updated_at"])


def _handle_succeeded(intent):
    payment = (
        Payment.objects.select_for_update()
        .filter(provider="stripe", provider_payment_id=intent["id"])
        .first()
    )
    if payment is None:
        raise PaymentMismatch(message="No local payment matches this intent.")

    order = Order.objects.select_for_update().get(pk=payment.order_id)

    metadata = intent.get("metadata") or {}
    reconciled = (
        int(intent["amount"]) == payment.amount_minor
        and str(intent["currency"]).upper() == order.currency
        and metadata.get("order_id") == str(order.id)
    )
    if not reconciled:
        # Deliberately no write here. Raising aborts the surrounding transaction, so
        # anything saved on this path is rolled back with it — the payment would be
        # left stale at "processing" while only the webhook row recorded the failure.
        # The id travels on the exception and the caller records the failure once the
        # rollback is complete.
        mismatch = PaymentMismatch()
        mismatch.payment_id = payment.pk
        raise mismatch

    if order.payment_status == "paid":
        if payment.status != "succeeded":
            payment.status = "succeeded"
            payment.paid_at = payment.paid_at or timezone.now()
            payment.save(update_fields=["status", "paid_at", "updated_at"])
        return

    payment.status = "succeeded"
    payment.paid_at = timezone.now()
    payment.save(update_fields=["status", "paid_at", "updated_at"])

    order.payment_status = "paid"
    order.status = "paid"
    order.save(update_fields=["payment_status", "status", "updated_at"])
    consume_promo_for_order(order)
    create_commission_for_order(order)
    enqueue_provisioning_for_order(order)
    queue_notification(
        template_code="order-confirmation",
        recipient=order.customer_email,
        idempotency_key=f"notify:order-confirmation:{order.id}",
        user=order.user,
        order=order,
    )


def reconcile_stuck_payments(*, older_than_minutes=10, limit=20):
    """Finish orders whose `payment_intent.succeeded` webhook never arrived.

    A webhook is best-effort. If the delivery is lost, rejected or simply late, nothing
    else in this system ever learns the payment succeeded: the money sits in Stripe, the
    order stays `pending_payment`, no eSIM is bought and the customer watches "Waiting for
    your payment to be confirmed..." for ever. That is not hypothetical — two real charges
    were taken and never delivered because `STRIPE_WEBHOOK_SECRET` did not match the
    endpoint sending events, and every delivery was rejected with a 400. Nothing recovered
    them, because nothing was looking.

    So this asks the opposite question. Instead of waiting to be told, it takes payments
    that have been stuck long enough to be suspicious and asks Stripe directly what
    happened. When Stripe says the money moved, it runs `_handle_succeeded` — the SAME
    function the webhook runs, not a parallel implementation that could drift from it.

    Safety, in the order it matters:

    * Provisioning cannot happen twice. `_handle_succeeded` returns early once the order
      is `paid`, so a webhook that arrives late finds the work already done.
    * A concurrent webhook cannot interleave. Both paths take `select_for_update` on the
      same Payment row, so they serialise and the loser sees `paid`.
    * `PaymentMismatch` is caught OUTSIDE the transaction, exactly as `handle_webhook_event`
      does. Writing the quarantine inside would roll it back with the transaction and
      leave the payment stale at `processing` with the failure recorded nowhere.
    * One unreachable or malformed payment cannot stop the batch — each is isolated.
    * `limit` bounds the Stripe calls per pass, so a large backlog drains over several
      passes instead of tripping rate limits.

    `older_than_minutes` must stay comfortably longer than a normal delivery, which is
    seconds. Reconciling too eagerly would race healthy webhooks for no benefit.
    """
    cutoff = timezone.now() - timedelta(minutes=older_than_minutes)
    candidates = list(
        Payment.objects.filter(
            provider="stripe",
            status="processing",
            provider_payment_id__isnull=False,
            created_at__lte=cutoff,
            order__payment_status="pending",
        ).order_by("created_at")[:limit]
    )
    if not candidates:
        return 0

    gateway = gateway_module.get_gateway()
    reconciled = 0
    for payment in candidates:
        try:
            intent = gateway.retrieve_payment_intent(payment.provider_payment_id)
        except Exception as exc:
            # Stripe unreachable or answering oddly. Leave the row alone; the next pass
            # retries it. Isolated so one bad id cannot strand the rest of the batch.
            logger.warning(
                "Reconciliation could not read intent %s: %s", payment.provider_payment_id, exc
            )
            continue

        status = str(intent.get("status") or "")
        if status != "succeeded":
            # Genuinely unpaid, still in progress, or cancelled. Not this function's
            # business — it exists to rescue money that MOVED, and marking an order failed
            # from here would fight the `payment_intent.payment_failed` webhook.
            continue

        if intent.get("refunded") or (intent.get("amount_refunded") or 0) > 0:
            # A refund leaves `status` at "succeeded" for ever, so this is the only thing
            # standing between a refunded charge and a free eSIM. Loud, because it means an
            # order was paid, refunded and never delivered — someone should look at it.
            logger.warning(
                "Skipping refunded intent %s on order %s — paid then refunded, not delivered",
                payment.provider_payment_id, payment.order_id,
            )
            continue

        try:
            with transaction.atomic():
                _handle_succeeded(intent)
        except PaymentMismatch as exc:
            payment_id = getattr(exc, "payment_id", None)
            if payment_id is not None:
                Payment.objects.filter(pk=payment_id, status="processing").update(
                    status="failed", failure_code="reconciliation_mismatch"
                )
            logger.error(
                "Reconciliation mismatch on intent %s: %s",
                payment.provider_payment_id, exc.message,
            )
            continue
        except Exception as exc:
            logger.exception(
                "Reconciliation failed for intent %s: %s", payment.provider_payment_id, exc
            )
            continue

        reconciled += 1
        # WARNING, not INFO: reaching here means a webhook that should have arrived did
        # not, and the money was only delivered because something went looking for it.
        logger.warning(
            "Reconciled order %s from intent %s — its webhook never arrived",
            payment.order_id, payment.provider_payment_id,
        )
    return reconciled


def _handle_failed(intent):
    payment = (
        Payment.objects.select_for_update()
        .filter(provider="stripe", provider_payment_id=intent["id"])
        .first()
    )
    if payment is None:
        return
    order = Order.objects.select_for_update().get(pk=payment.order_id)
    if order.payment_status == "paid":
        return
    payment.status = "failed"
    payment.failure_code = (intent.get("last_payment_error") or {}).get("code") or "payment_failed"
    payment.save(update_fields=["status", "failure_code", "updated_at"])
    order.payment_status = "failed"
    order.save(update_fields=["payment_status", "updated_at"])
    release_promo_for_order(order)


def _complete_zero_total(order_id):
    order = Order.objects.select_for_update().get(pk=order_id)
    if order.payment_status == "paid":
        return
    order.payment_status = "paid"
    order.status = "paid"
    order.metadata = {**(order.metadata or {}), "zero_total": True}
    order.save(update_fields=["payment_status", "status", "metadata", "updated_at"])
    consume_promo_for_order(order)
    create_commission_for_order(order)
    enqueue_provisioning_for_order(order)
    queue_notification(
        template_code="order-confirmation",
        recipient=order.customer_email,
        idempotency_key=f"notify:order-confirmation:{order.id}",
        user=order.user,
        order=order,
    )


def _redact(event):
    obj = (event.get("data") or {}).get("object") or {}
    return {
        "id": event.get("id"),
        "type": event.get("type"),
        "object_id": obj.get("id"),
        "amount": obj.get("amount"),
        "currency": obj.get("currency"),
    }


REFUND_ATTEMPT_STATES = ["pending", "processing", "succeeded"]


def _refund_idempotency_key(payment, allocations, attempt):
    """A key that is stable across retries but distinct across deliberate refunds.

    Stripe deduplicates by idempotency key, so a retry after "provider succeeded, local
    write failed" must present the *same* key or it buys a second refund. A random key
    never could. Hashing the allocation set alone would go too far the other way — it
    would permanently block a legitimate second refund of the same item for the same
    amount. ``attempt`` is the number of refunds already committed against this payment:
    a rolled-back attempt leaves it unchanged (so the retry matches), while a committed
    one moves it on (so the next refund is free to proceed).
    """
    canonical = json.dumps(
        {
            "payment": str(payment.id),
            "attempt": attempt,
            "allocations": sorted(
                (str(a["order_item_id"]), int(a["amount_minor"])) for a in allocations
            ),
        },
        sort_keys=True,
    )
    digest = hashlib.sha256(canonical.encode()).hexdigest()[:32]
    return f"refund:{payment.id}:{digest}"


def create_refund(*, payment, allocations, reason=None):
    with transaction.atomic():
        payment = Payment.objects.select_for_update().get(pk=payment.pk)
        order = Order.objects.select_for_update().get(pk=payment.order_id)
        total = sum(int(a["amount_minor"]) for a in allocations)
        if total <= 0:
            raise Conflict(message="Refund amount must be positive.")

        prior = (
            Refund.objects.filter(
                payment=payment, status__in=["pending", "processing", "succeeded"]
            ).aggregate(s=Sum("amount_minor"))["s"]
            or 0
        )
        if prior + total > payment.amount_minor:
            raise RefundLimitExceeded()

        for alloc in allocations:
            item = OrderItem.objects.filter(pk=alloc["order_item_id"], order=order).first()
            if item is None:
                raise Conflict(
                    message="Order item does not belong to this order.",
                    error_code="not_found",
                    status_code=404,
                )
            item_prior = (
                RefundItem.objects.filter(
                    order_item=item,
                    refund__status__in=["pending", "processing", "succeeded"],
                ).aggregate(s=Sum("amount_minor"))["s"]
                or 0
            )
            if item_prior + int(alloc["amount_minor"]) > item.unit_amount_minor:
                raise RefundLimitExceeded()

        attempt = Refund.objects.filter(
            payment=payment, status__in=REFUND_ATTEMPT_STATES
        ).count()
        idempotency_key = _refund_idempotency_key(payment, allocations, attempt)
        existing = Refund.objects.filter(idempotency_key=idempotency_key).first()
        if existing is not None:
            return existing

        refund = Refund.objects.create(
            payment=payment,
            provider="stripe",
            idempotency_key=idempotency_key,
            amount_minor=total,
            currency=order.currency,
            reason=reason,
            status="pending",
        )
        for alloc in allocations:
            RefundItem.objects.create(
                refund=refund,
                order_item_id=alloc["order_item_id"],
                amount_minor=int(alloc["amount_minor"]),
            )

        result = gateway_module.get_gateway().create_refund(
            payment_intent_id=payment.provider_payment_id,
            amount_minor=total,
            idempotency_key=idempotency_key,
        )
        refund.provider_refund_id = result["id"]
        if result["status"] == "succeeded":
            refund.status = "succeeded"
            refund.completed_at = timezone.now()
        else:
            refund.status = "processing"
        refund.save(
            update_fields=["provider_refund_id", "status", "completed_at", "updated_at"]
        )

        if refund.status == "succeeded":
            _apply_successful_refund(payment, order, total)
            queue_notification(
                template_code="refund-confirmation",
                recipient=order.customer_email,
                idempotency_key=f"notify:refund-confirmation:{refund.id}",
                user=order.user,
                order=order,
            )
        return refund


def _apply_successful_refund(payment, order, refunded_minor):
    total_refunded = (
        Refund.objects.filter(payment=payment, status="succeeded").aggregate(
            s=Sum("amount_minor")
        )["s"]
        or 0
    )
    if total_refunded >= payment.amount_minor:
        payment.status = "refunded"
        order.payment_status = "refunded"
        order.status = "refunded"
    else:
        payment.status = "partially_refunded"
        order.payment_status = "partially_refunded"
        order.status = "partially_refunded"
    payment.save(update_fields=["status", "updated_at"])
    order.save(update_fields=["payment_status", "status", "updated_at"])
    reverse_commission_for_order(order, refunded_minor)
