# Generated by Django 5.2.16 on 2026-07-22 13:41

import apps.common.models
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_organizationmember'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_token_hash', models.BinaryField(blank=True, max_length=32, null=True, unique=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(default='esim', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart')),
                ('catalog_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.catalogplan')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=40, unique=True)),
                ('promo_code_snapshot', models.CharField(blank=True, max_length=120, null=True)),
                ('customer_email', apps.common.models.CIEmailField(max_length=254)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_minor', models.BigIntegerField()),
                ('discount_minor', models.BigIntegerField(default=0)),
                ('tax_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('payment_status', models.CharField(max_length=30)),
                ('fulfillment_status', models.CharField(max_length=30)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('buyer_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.organization')),
                ('referring_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referred_orders', to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(max_length=20)),
                ('product_code', models.CharField(max_length=120)),
                ('supplier_package_code', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=240)),
                ('country_iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('country_name', models.CharField(blank=True, max_length=120, null=True)),
                ('plan_type', models.CharField(blank=True, max_length=20, null=True)),
                ('data_limit_mb', models.BigIntegerField(blank=True, null=True)),
                ('daily_high_speed_mb', models.BigIntegerField(blank=True, null=True)),
                ('validity_days', models.IntegerField(blank=True, null=True)),
                ('traffic_policy', models.TextField(blank=True, null=True)),
                ('network_names', models.JSONField(default=list)),
                ('unit_amount_minor', models.BigIntegerField()),
                ('wholesale_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('catalog_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.catalogplan')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.supplier')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', apps.common.models.CITextField(unique=True)),
                ('discount_type', models.CharField(max_length=20)),
                ('discount_value', models.BigIntegerField()),
                ('discount_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('maximum_discount_minor', models.BigIntegerField(blank=True, null=True)),
                ('minimum_order_minor', models.BigIntegerField(default=0)),
                ('commission_type', models.CharField(blank=True, max_length=20, null=True)),
                ('commission_value', models.BigIntegerField(blank=True, null=True)),
                ('commission_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('per_customer_limit', models.IntegerField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promo_codes', to='accounts.organization')),
            ],
            options={
                'db_table': 'promo_codes',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.promocode'),
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_email_hash', models.BinaryField(max_length=32)),
                ('status', models.CharField(default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='promo_redemption', to='orders.order')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='orders.promocode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promo_redemptions',
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'converted', 'expired', 'abandoned'))), name='cart_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('guest_token_hash__isnull', True)), models.Q(('user__isnull', True), ('guest_token_hash__isnull', False)), _connector='OR'), name='cart_identity_user_xor_guest'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', True), ('user__isnull', False), _connector='OR'), name='cart_org_requires_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('user__isnull', False)), fields=('user', 'currency'), name='one_active_cart_per_user_currency'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__in', ('esim',))), name='cart_item_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 1000)), name='cart_item_quantity_range'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'esim'), _negated=True), ('catalog_plan__isnull', False), _connector='OR'), name='cart_item_esim_requires_plan'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('catalog_plan__isnull', False)), fields=('cart', 'catalog_plan'), name='unique_plan_per_cart'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__in', ('esim', 'topup'))), name='order_item_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount_minor__gte', 0)), name='order_item_unit_amount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type__in', ('fixed', 'percentage_bps'))), name='promo_discount_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'percentage_bps'), _negated=True), ('discount_value__lte', 10000), _connector='OR'), name='promo_percentage_within_bounds'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'fixed'), _negated=True), ('discount_currency__isnull', False), _connector='OR'), name='promo_fixed_requires_currency'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('organization__isnull', True), models.Q(('commission_type__isnull', False), ('commission_value__isnull', False)), _connector='OR'), name='promo_agency_requires_commission'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('commission_type__isnull', True), ('commission_type__in', ('percentage_bps', 'fixed')), _connector='OR'), name='promo_commission_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('commission_type', 'fixed'), _negated=True), ('commission_currency__isnull', False), _connector='OR'), name='promo_fixed_commission_requires_currency'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('starts_at__lte', models.F('ends_at')), _connector='OR'), name='promo_dates_ordered'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='orders_status_7dca14_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_minor__gte', 0)), name='order_subtotal_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_minor__gte', 0)), name='order_discount_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_minor__lte', models.F('subtotal_minor'))), name='order_discount_le_subtotal'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('tax_minor__gte', 0)), name='order_tax_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_minor__gte', 0)), name='order_total_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_minor', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_minor'), '-', models.F('discount_minor')), '+', models.F('tax_minor')))), name='order_total_balances'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending_payment', 'paid', 'fulfilling', 'partially_fulfilled', 'fulfilled', 'cancelled', 'partially_refunded', 'refunded', 'failed'))), name='order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('payment_status__in', ('pending', 'processing', 'paid', 'failed', 'cancelled', 'partially_refunded', 'refunded'))), name='order_payment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('fulfillment_status__in', ('pending', 'processing', 'partially_delivered', 'delivered', 'failed', 'cancelled'))), name='order_fulfillment_status_valid'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['promo_code', 'status'], name='promo_redem_promo_c_63855e_idx'),
        ),
        migrations.AddConstraint(
            model_name='promoredemption',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('reserved', 'consumed', 'released', 'cancelled'))), name='promo_redemption_status_valid'),
        ),
    ]
