# Generated by Django 5.2.16 on 2026-07-22 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esims', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('recipient', models.CharField(max_length=320)),
                ('template_code', models.CharField(max_length=80)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('esim_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='esims.esimprofile')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='notificatio_status_55722f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('queued', 'processing', 'sent', 'delivered', 'retrying', 'failed', 'cancelled'))), name='notification_status_valid')],
            },
        ),
    ]
