# Generated by Django 5.2.16 on 2026-07-22 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_topupproduct'),
        ('esims', '0002_topupfulfillment'),
        ('orders', '0002_notification'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cart_item_type_valid',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='cart_item_esim_requires_plan',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='target_esim_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='esims.esimprofile'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='topup_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='catalog.topupproduct'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topup_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.topupproduct'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__in', ('esim', 'topup'))), name='cart_item_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'esim'), _negated=True), models.Q(('catalog_plan__isnull', False), ('topup_product__isnull', True), ('target_esim_profile__isnull', True)), _connector='OR'), name='cart_item_esim_requires_plan'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_type', 'topup'), _negated=True), models.Q(('topup_product__isnull', False), ('target_esim_profile__isnull', False), ('catalog_plan__isnull', True), ('quantity', 1)), _connector='OR'), name='cart_item_topup_requires_target'),
        ),
    ]
