# Generated by Django 5.2.16 on 2026-07-28 17:27

from django.db import migrations, models


def classify_existing_codes(apps, schema_editor):
    """Assign ``kind`` to codes created before the field existed.

    An agency-owned code carrying no discount was already, in intent, a pure attribution
    code — so it becomes ``tracking``. Everything else stays ``discount``. Codes that give
    a real discount are never reclassified, because ``tracking`` would then violate the
    zero-discount constraint added below.
    """
    PromoCode = apps.get_model("orders", "PromoCode")
    PromoCode.objects.filter(organization__isnull=False, discount_value=0).update(
        kind="tracking"
    )


def revert_classification(apps, schema_editor):
    PromoCode = apps.get_model("orders", "PromoCode")
    PromoCode.objects.update(kind="discount")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_organizatio_status_e97117_idx_and_more'),
        ('orders', '0003_remove_cartitem_cart_item_type_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='kind',
            field=models.CharField(default='discount', max_length=20),
        ),
        migrations.RunPython(classify_existing_codes, revert_classification),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('discount', 'tracking'))), name='promo_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'tracking'), _negated=True), ('discount_value', 0), _connector='OR'), name='promo_tracking_has_no_discount'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'tracking'), _negated=True), ('organization__isnull', False), _connector='OR'), name='promo_tracking_requires_organization'),
        ),
    ]
