# Generated by Django 5.2.16 on 2026-08-03 16:33

from decimal import Decimal

from django.db import migrations, models


def backfill_usd_orders(apps, schema_editor):
    """Every existing order is USD, so its base amounts are its local amounts.

    Lossless and exact — no conversion is involved, because there is nothing to convert.
    Doing it here means reports and commissions can read base_* unconditionally instead of
    carrying a "None means USD" special case forever.
    """
    Order = apps.get_model("orders", "Order")
    OrderItem = apps.get_model("orders", "OrderItem")
    Order.objects.filter(base_total_minor__isnull=True).update(
        base_currency=models.F("currency"),
        base_subtotal_minor=models.F("subtotal_minor"),
        base_total_minor=models.F("total_minor"),
        fx_rate_used=Decimal("1"),
    )
    OrderItem.objects.filter(base_unit_amount_minor__isnull=True).update(
        base_unit_amount_minor=models.F("unit_amount_minor")
    )


def unbackfill(apps, schema_editor):
    """Reversible: the columns are dropped by the schema operations anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_promocode_kind_promocode_promo_kind_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='base_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='base_subtotal_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='base_total_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fx_rate_used',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='base_unit_amount_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
            migrations.RunPython(backfill_usd_orders, unbackfill),
    ]
