# Generated by Django 5.2.16 on 2026-07-22 13:11

import apps.common.models
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('region', models.CharField(max_length=80)),
                ('flag_emoji', models.CharField(blank=True, max_length=16, null=True)),
                ('timezone', models.CharField(blank=True, max_length=80, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('homepage_badge', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
                'indexes': [models.Index(fields=['is_active', 'is_popular', 'sort_order'], name='countries_is_acti_663b73_idx'), models.Index(fields=['region', 'is_active', 'name'], name='countries_region_82397b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('iso2__regex', '^[A-Z]{2}$')), name='country_iso2_uppercase'), models.CheckConstraint(condition=models.Q(('homepage_badge__isnull', True), ('homepage_badge__in', ['popular', 'best_value']), _connector='OR'), name='country_homepage_badge_valid'), models.CheckConstraint(condition=models.Q(('sort_order__gte', 0)), name='country_sort_order_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(default='active', max_length=20)),
                ('api_base_url', models.CharField(blank=True, max_length=500, null=True)),
                ('support_email', apps.common.models.CIEmailField(blank=True, max_length=254, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'suppliers',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ('active', 'paused', 'disabled'))), name='supplier_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='CatalogPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=120, unique=True)),
                ('supplier_package_code', models.CharField(max_length=120)),
                ('plan_type', models.CharField(max_length=20)),
                ('day_count', models.IntegerField(blank=True, null=True)),
                ('display_name', models.CharField(max_length=240)),
                ('data_limit_mb', models.BigIntegerField(blank=True, null=True)),
                ('daily_high_speed_mb', models.BigIntegerField(blank=True, null=True)),
                ('validity_days', models.IntegerField()),
                ('traffic_policy', models.TextField(blank=True, null=True)),
                ('activation_policy', models.TextField(blank=True, null=True)),
                ('hotspot_supported', models.BooleanField(blank=True, null=True)),
                ('network_names', models.JSONField(default=list)),
                ('topup_supported', models.BooleanField(default=False)),
                ('retail_amount_minor', models.BigIntegerField()),
                ('wholesale_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(default='paused', max_length=20)),
                ('badge', models.CharField(blank=True, max_length=20, null=True)),
                ('tier', models.CharField(blank=True, max_length=20, null=True)),
                ('is_default_selected', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('supplier_verified_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_metadata', models.JSONField(default=dict)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='catalog.country')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='catalog.supplier')),
            ],
            options={
                'db_table': 'catalog_plans',
                'indexes': [models.Index(fields=['country', 'status', 'sort_order'], name='catalog_pla_country_2da43a_idx'), models.Index(fields=['supplier', 'supplier_package_code'], name='catalog_pla_supplie_d6cbf7_idx'), models.Index(fields=['status'], name='catalog_pla_status_9db0b0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('plan_type__in', ('fixed', 'daily'))), name='catalog_plan_type_valid'), models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'paused', 'active', 'retired'))), name='catalog_plan_status_valid'), models.CheckConstraint(condition=models.Q(('badge__isnull', True), ('badge__in', ['popular', 'value']), _connector='OR'), name='catalog_plan_badge_valid'), models.CheckConstraint(condition=models.Q(('validity_days__gt', 0)), name='catalog_plan_validity_positive'), models.CheckConstraint(condition=models.Q(('retail_amount_minor__gt', 0)), name='catalog_plan_retail_positive'), models.CheckConstraint(condition=models.Q(('wholesale_amount_minor__isnull', True), ('wholesale_amount_minor__gte', 0), _connector='OR'), name='catalog_plan_wholesale_nonneg'), models.CheckConstraint(condition=models.Q(models.Q(('plan_type', 'fixed'), _negated=True), models.Q(('data_limit_mb__gt', 0), ('daily_high_speed_mb__isnull', True), ('day_count__isnull', True)), _connector='OR'), name='catalog_plan_fixed_shape'), models.CheckConstraint(condition=models.Q(models.Q(('plan_type', 'daily'), _negated=True), models.Q(('daily_high_speed_mb__gt', 0), ('data_limit_mb__isnull', True), ('day_count', models.F('validity_days'))), _connector='OR'), name='catalog_plan_daily_shape'), models.UniqueConstraint(condition=models.Q(('is_default_selected', True), models.Q(('status', 'retired'), _negated=True)), fields=('country',), name='one_default_plan_per_country')],
            },
        ),
    ]
