# Generated by Django 5.2.16 on 2026-07-22 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=120, unique=True)),
                ('supplier_package_code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=240)),
                ('data_amount_mb', models.BigIntegerField()),
                ('validity_days', models.IntegerField(blank=True, null=True)),
                ('retail_amount_minor', models.BigIntegerField()),
                ('wholesale_amount_minor', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(default='paused', max_length=20)),
                ('supplier_metadata', models.JSONField(default=dict)),
                ('base_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_products', to='catalog.catalogplan')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_products', to='catalog.supplier')),
            ],
            options={
                'db_table': 'topup_products',
                'indexes': [models.Index(fields=['supplier', 'status'], name='topup_produ_supplie_495d4e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_amount_mb__gt', 0)), name='topup_data_positive'), models.CheckConstraint(condition=models.Q(('validity_days__isnull', True), ('validity_days__gt', 0), _connector='OR'), name='topup_validity_positive'), models.CheckConstraint(condition=models.Q(('retail_amount_minor__gt', 0)), name='topup_retail_positive'), models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'paused', 'active', 'retired'))), name='topup_status_valid')],
            },
        ),
    ]
