# Generated by Django 5.2.16 on 2026-08-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_topupproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(max_length=60)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fx_rates',
                'indexes': [models.Index(fields=['base_currency', 'quote_currency', '-fetched_at'], name='fx_rate_latest_idx')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'fetched_at'), name='fx_rate_unique_per_fetch'), models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='fx_rate_positive')],
            },
        ),
    ]
