/**
 * Related destinations shown under each country page, by real travel corridor.
 *
 * Replaces the alphabetical-neighbour rotation that produced the previous "Continue your
 * trip" rows: with it, Albania suggested Austria and Belgium, South Africa received one
 * inbound link on the whole site and the ten written pages barely linked to each other.
 * Lists were taken from the per-country internal-link recommendations in
 * support_docs/seo-research/content_plan_*.md. Order is display order; the repository
 * fills any short row from the same region. A slug missing from the catalogue is ignored.
 */
export const RELATED_SLUGS = {
  "albania": ["montenegro", "serbia", "bosnia-and-herzegovina"],
  "australia": ["new-zealand", "indonesia", "singapore", "thailand", "south-africa"],
  "austria": ["germany", "hungary", "switzerland", "czech-republic"],
  "azerbaijan": ["georgia", "kazakhstan", "uzbekistan"],
  "bahrain": ["saudi-arabia", "qatar", "kuwait", "united-arab-emirates", "oman"],
  "bangladesh": ["india", "nepal", "sri-lanka"],
  "belgium": ["france", "germany", "netherlands"],
  "bosnia-and-herzegovina": ["albania", "croatia", "montenegro", "serbia"],
  "brazil": ["mexico", "united-states", "canada"],
  "brunei-darussalam": ["cambodia", "laos", "malaysia", "singapore"],
  "bulgaria": ["greece", "romania", "serbia", "north-macedonia"],
  "cambodia": ["laos", "thailand", "vietnam"],
  "canada": ["united-states", "mexico", "united-kingdom"],
  "china": ["hong-kong", "japan", "kazakhstan", "macao", "pakistan"],
  "croatia": ["greece", "italy", "montenegro", "bosnia-and-herzegovina"],
  "cyprus": ["greece", "italy", "malta", "united-kingdom", "israel"],
  "czech-republic": ["austria", "germany", "hungary", "poland"],
  "egypt": ["jordan", "israel", "saudi-arabia", "morocco", "turkey", "south-africa"],
  "france": ["belgium", "germany", "netherlands", "switzerland"],
  "georgia": ["azerbaijan", "kazakhstan", "uzbekistan", "turkey"],
  "germany": ["austria", "belgium", "netherlands", "czech-republic"],
  "greece": ["cyprus", "italy", "malta", "united-kingdom", "turkey", "north-macedonia"],
  "hong-kong": ["china", "macao", "philippines"],
  "hungary": ["austria", "romania"],
  "india": ["bangladesh", "maldives", "nepal", "sri-lanka", "united-arab-emirates"],
  "indonesia": ["malaysia", "singapore", "thailand", "brunei-darussalam", "australia"],
  "ireland": ["france", "netherlands", "portugal", "united-states"],
  "israel": ["jordan", "egypt", "cyprus", "united-arab-emirates"],
  "italy": ["france", "greece", "spain", "switzerland"],
  "japan": ["china", "hong-kong", "south-korea", "united-states"],
  "jordan": ["egypt", "israel", "saudi-arabia", "united-arab-emirates"],
  "kazakhstan": ["azerbaijan", "china", "georgia", "uzbekistan"],
  "kuwait": ["saudi-arabia", "bahrain", "qatar", "united-arab-emirates", "oman"],
  "laos": ["cambodia", "thailand", "vietnam"],
  "macao": ["china", "hong-kong"],
  "malaysia": ["indonesia", "singapore", "thailand", "brunei-darussalam"],
  "maldives": ["india", "singapore", "sri-lanka"],
  "malta": ["cyprus", "greece", "italy", "united-kingdom"],
  "mexico": ["united-states", "canada", "brazil"],
  "montenegro": ["serbia", "albania", "bosnia-and-herzegovina", "croatia"],
  "morocco": ["spain", "portugal", "tunisia", "egypt", "turkey"],
  "nepal": ["bangladesh", "india", "sri-lanka", "thailand"],
  "netherlands": ["belgium", "france", "germany"],
  "new-zealand": ["australia", "singapore", "united-kingdom"],
  "north-macedonia": ["albania", "greece", "serbia", "bosnia-and-herzegovina"],
  "oman": ["united-arab-emirates", "saudi-arabia", "qatar", "bahrain"],
  "pakistan": ["china", "india", "uzbekistan"],
  "philippines": ["hong-kong", "malaysia", "thailand", "vietnam"],
  "poland": ["germany", "hungary", "united-kingdom", "czech-republic"],
  "portugal": ["montenegro", "spain", "united-kingdom", "morocco"],
  "qatar": ["united-arab-emirates", "saudi-arabia", "bahrain", "oman"],
  "romania": ["bulgaria", "hungary", "montenegro", "serbia"],
  "saudi-arabia": ["united-arab-emirates", "bahrain", "qatar", "oman", "kuwait", "jordan"],
  "serbia": ["albania", "montenegro", "bosnia-and-herzegovina", "north-macedonia"],
  "singapore": ["indonesia", "malaysia", "maldives", "australia", "new-zealand"],
  "south-africa": ["united-kingdom", "united-arab-emirates", "egypt", "australia"],
  "south-korea": ["japan", "philippines", "vietnam"],
  "spain": ["france", "italy", "portugal", "switzerland", "morocco"],
  "sri-lanka": ["bangladesh", "india", "maldives", "nepal"],
  "switzerland": ["austria", "italy"],
  "thailand": ["cambodia", "laos", "malaysia", "vietnam", "australia"],
  "tunisia": ["morocco", "egypt", "italy", "turkey"],
  "turkey": ["greece", "georgia", "egypt", "morocco", "united-kingdom"],
  "united-arab-emirates": ["oman", "saudi-arabia", "qatar", "bahrain", "india", "south-africa"],
  "united-kingdom": ["cyprus", "ireland", "switzerland", "united-states", "south-africa", "new-zealand"],
  "united-states": ["canada", "mexico", "united-kingdom", "japan"],
  "uzbekistan": ["azerbaijan", "georgia", "kazakhstan", "pakistan"],
  "vietnam": ["cambodia", "laos", "thailand"],
};
