# Generated by Django 5.2.16 on 2026-07-22 13:41

import apps.common.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('organization_type', models.CharField(max_length=30)),
                ('billing_email', apps.common.models.CIEmailField(max_length=254)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('default_commission_type', models.CharField(blank=True, max_length=20, null=True)),
                ('default_commission_value', models.BigIntegerField(blank=True, null=True)),
                ('commission_currency', models.CharField(blank=True, max_length=3, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'organizations',
                'constraints': [models.CheckConstraint(condition=models.Q(('organization_type__in', ('travel_agency', 'business', 'affiliate'))), name='organization_type_valid'), models.CheckConstraint(condition=models.Q(('default_commission_type__isnull', True), ('default_commission_type__in', ('percentage_bps', 'fixed')), _connector='OR'), name='organization_commission_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_members',
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_org_member'), models.CheckConstraint(condition=models.Q(('role__in', ('owner', 'admin', 'buyer', 'viewer'))), name='org_member_role_valid'), models.CheckConstraint(condition=models.Q(('status__in', ('invited', 'active', 'disabled'))), name='org_member_status_valid')],
            },
        ),
    ]
