# Generated by Django 5.2.16 on 2026-07-22 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_organizationmember'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount_minor', models.BigIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=40, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=240, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='accounts.organization')),
            ],
            options={
                'db_table': 'commission_payouts',
            },
        ),
        migrations.CreateModel(
            name='PartnerCommission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_type', models.CharField(max_length=20)),
                ('commission_value_snapshot', models.BigIntegerField()),
                ('commissionable_minor', models.BigIntegerField()),
                ('commission_minor', models.BigIntegerField()),
                ('reversed_minor', models.BigIntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='orders.order')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='accounts.organization')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='accounts.commissionpayout')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='orders.promocode')),
            ],
            options={
                'db_table': 'partner_commissions',
            },
        ),
        migrations.AddConstraint(
            model_name='commissionpayout',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'approved', 'processing', 'paid', 'failed', 'cancelled'))), name='payout_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='partnercommission',
            constraint=models.UniqueConstraint(fields=('organization', 'order'), name='unique_org_order_commission'),
        ),
        migrations.AddConstraint(
            model_name='partnercommission',
            constraint=models.CheckConstraint(condition=models.Q(('reversed_minor__gte', 0), ('reversed_minor__lte', models.F('commission_minor'))), name='commission_reversed_bounds'),
        ),
        migrations.AddConstraint(
            model_name='partnercommission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'available', 'approved', 'paid', 'cancelled', 'reversed'))), name='commission_status_valid'),
        ),
    ]
