# Generated by Django 5.2.16 on 2026-07-28 17:03

from django.db import migrations, models

VALID_STATUSES = ("pending", "active", "suspended", "rejected", "closed")


def normalise_statuses(apps, schema_editor):
    """Coerce any legacy status value so the new CheckConstraint can be applied.

    ``organizations.status`` was previously unconstrained free text. Adding the constraint
    against a row holding an unexpected value would abort the migration, so anything
    unrecognised is parked at ``pending`` (the safest state: it cannot transact).
    """
    Organization = apps.get_model("accounts", "Organization")
    Organization.objects.exclude(status__in=VALID_STATUSES).update(status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_commissionpayout_partnercommission_and_more'),
    ]

    operations = [
        migrations.RunPython(normalise_statuses, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', 'organization_type'], name='organizatio_status_e97117_idx'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'active', 'suspended', 'rejected', 'closed'))), name='organization_status_valid'),
        ),
    ]
