# Generated by Django 5.2.16 on 2026-07-22 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('external_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=120)),
                ('payload_redacted', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField()),
                ('status', models.CharField(max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='webhook_eve_status_8017be_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='unique_provider_event'), models.CheckConstraint(condition=models.Q(('status__in', ('received', 'processing', 'processed', 'failed', 'rejected'))), name='webhook_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('provider_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_checkout_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('failure_code', models.CharField(blank=True, max_length=120, null=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['order', 'status'], name='payments_order_i_3d4604_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='payment_amount_positive'), models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'processing', 'succeeded', 'failed', 'cancelled', 'refunded', 'partially_refunded'))), name='payment_status_valid'), models.UniqueConstraint(condition=models.Q(('provider_payment_id__isnull', False)), fields=('provider', 'provider_payment_id'), name='unique_provider_payment_id'), models.UniqueConstraint(condition=models.Q(('provider_checkout_session_id__isnull', False)), fields=('provider', 'provider_checkout_session_id'), name='unique_provider_checkout_session_id')],
            },
        ),
    ]
