# Generated by Django 5.2.16 on 2026-07-22 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=30)),
                ('provider_refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'refunds',
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_minor', models.BigIntegerField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='orders.orderitem')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='payments.refund')),
            ],
            options={
                'db_table': 'refund_items',
            },
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'processing', 'succeeded', 'failed', 'cancelled'))), name='refund_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_refund_id__isnull', False)), fields=('provider', 'provider_refund_id'), name='unique_provider_refund_id'),
        ),
        migrations.AddConstraint(
            model_name='refunditem',
            constraint=models.UniqueConstraint(fields=('refund', 'order_item'), name='unique_refund_order_item'),
        ),
        migrations.AddConstraint(
            model_name='refunditem',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='refund_item_amount_positive'),
        ),
    ]
